
CREATE TABLE distrito (
  id int NOT NULL,
  codigoProvincia int DEFAULT NULL,
  codigoCanton int DEFAULT NULL,
  codigo int DEFAULT NULL,
  distrito varchar(70) DEFAULT NULL,
  PRIMARY KEY (id)
)

INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('1', '1', '01', '01', 'CARMEN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('2', '1', '01', '02', 'MERCED');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('3', '1', '01', '03', 'HOSPITAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('4', '1', '01', '04', 'CATEDRAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('5', '1', '01', '05', 'ZAPOTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('6', '1', '01', '06', 'SAN FRANCISCO DE DOS RÍOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('7', '1', '01', '07', 'URUCA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('8', '1', '01', '08', 'MATA REDONDA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('9', '1', '01', '09', 'PAVAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('10', '1', '01', '10', 'HATILLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('11', '1', '01', '11', 'SAN SEBASTIÁN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('12', '1', '02', '01', 'ESCAZÚ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('13', '1', '02', '02', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('14', '1', '02', '03', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('15', '1', '03', '01', 'DESAMPARADOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('16', '1', '03', '02', 'SAN MIGUEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('17', '1', '03', '03', 'SAN JUAN DE DIOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('18', '1', '03', '04', 'SAN RAFAEL ARRIBA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('19', '1', '03', '05', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('20', '1', '03', '06', 'FRAILES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('21', '1', '03', '07', 'PATARRÁ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('22', '1', '03', '08', 'SAN CRISTÓBAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('23', '1', '03', '09', 'ROSARIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('24', '1', '03', '10', 'DAMAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('25', '1', '03', '11', 'SAN RAFAEL ABAJO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('26', '1', '03', '12', 'GRAVILIAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('27', '1', '03', '13', 'LOS GUIDO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('28', '1', '04', '01', 'SANTIAGO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('29', '1', '04', '02', 'MERCEDES SUR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('30', '1', '04', '03', 'BARBACOAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('31', '1', '04', '04', 'GRIFO ALTO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('32', '1', '04', '05', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('33', '1', '04', '06', 'CANDELARITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('34', '1', '04', '07', 'DESAMPARADITOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('35', '1', '04', '08', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('36', '1', '04', '09', 'CHIRES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('37', '1', '05', '01', 'SAN MARCOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('38', '1', '05', '02', 'SAN LORENZO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('39', '1', '05', '03', 'SAN CARLOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('40', '1', '06', '01', 'ASERRI');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('41', '1', '06', '02', 'TARBACA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('42', '1', '06', '03', 'VUELTA DE JORCO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('43', '1', '06', '04', 'SAN GABRIEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('44', '1', '06', '05', 'LEGUA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('45', '1', '06', '06', 'MONTERREY');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('46', '1', '06', '07', 'SALITRILLOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('47', '1', '07', '01', 'COLÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('48', '1', '07', '02', 'GUAYABO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('49', '1', '07', '03', 'TABARCIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('50', '1', '07', '04', 'PIEDRAS NEGRAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('51', '1', '07', '05', 'PICAGRES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('52', '1', '07', '06', 'JARIS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('53', '1', '07', '07', 'QUITIRRISI');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('54', '1', '08', '01', 'GUADALUPE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('55', '1', '08', '02', 'SAN FRANCISCO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('56', '1', '08', '03', 'CALLE BLANCOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('57', '1', '08', '04', 'MATA DE PLÁTANO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('58', '1', '08', '05', 'IPÍS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('59', '1', '08', '06', 'RANCHO REDONDO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('60', '1', '08', '07', 'PURRAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('61', '1', '09', '01', 'SANTA ANA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('62', '1', '09', '02', 'SALITRAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('63', '1', '09', '03', 'POZOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('64', '1', '09', '04', 'URUCA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('65', '1', '09', '05', 'PIEDADES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('66', '1', '09', '06', 'BRASIL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('67', '1', '10', '01', 'ALAJUELITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('68', '1', '10', '02', 'SAN JOSECITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('69', '1', '10', '03', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('70', '1', '10', '04', 'CONCEPCIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('71', '1', '10', '05', 'SAN FELIPE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('72', '1', '11', '01', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('73', '1', '11', '02', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('74', '1', '11', '03', 'DULCE NOMBRE DE JESÚS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('75', '1', '11', '04', 'PATALILLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('76', '1', '11', '05', 'CASCAJAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('77', '1', '12', '01', 'SAN IGNACIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('78', '1', '12', '02', 'GUAITIL Villa');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('79', '1', '12', '03', 'PALMICHAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('80', '1', '12', '04', 'CANGREJAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('81', '1', '12', '05', 'SABANILLAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('82', '1', '13', '01', 'SAN JUAN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('83', '1', '13', '02', 'CINCO ESQUINAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('84', '1', '13', '03', 'ANSELMO LLORENTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('85', '1', '13', '04', 'LEON XIII');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('86', '1', '13', '05', 'COLIMA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('87', '1', '14', '01', 'SAN VICENTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('88', '1', '14', '02', 'SAN JERÓNIMO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('89', '1', '14', '03', 'LA TRINIDAD');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('90', '1', '15', '01', 'SAN PEDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('91', '1', '15', '02', 'SABANILLA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('92', '1', '15', '03', 'MERCEDES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('93', '1', '15', '04', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('94', '1', '16', '01', 'SAN PABLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('95', '1', '16', '02', 'SAN PEDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('96', '1', '16', '03', 'SAN JUAN DE MATA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('97', '1', '16', '04', 'SAN LUIS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('98', '1', '16', '05', 'CARARA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('99', '1', '17', '01', 'SANTA MARÍA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('100', '1', '17', '02', 'JARDÍN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('101', '1', '17', '03', 'COPEY');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('102', '1', '18', '01', 'CURRIDABAT');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('103', '1', '18', '02', 'GRANADILLA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('104', '1', '18', '03', 'SÁNCHEZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('105', '1', '18', '04', 'TIRRASES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('106', '1', '19', '01', 'SAN ISIDRO DE EL GENERAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('107', '1', '19', '02', 'EL GENERAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('108', '1', '19', '03', 'DANIEL FLORES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('109', '1', '19', '04', 'RIVAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('110', '1', '19', '05', 'SAN PEDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('111', '1', '19', '06', 'PLATANARES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('112', '1', '19', '07', 'PEJIBAYE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('113', '1', '19', '08', 'CAJÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('114', '1', '19', '09', 'BARÚ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('115', '1', '19', '10', 'RÍO NUEVO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('116', '1', '19', '11', 'PÁRAMO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('117', '1', '20', '01', 'SAN PABLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('118', '1', '20', '02', 'SAN ANDRÉS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('119', '1', '20', '03', 'LLANO BONITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('120', '1', '20', '04', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('121', '1', '20', '05', 'SANTA CRUZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('122', '1', '20', '06', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('123', '2', '21', '01', 'ALAJUELA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('124', '2', '21', '02', 'SAN JOSÉ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('125', '2', '21', '03', 'CARRIZAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('126', '2', '21', '04', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('127', '2', '21', '05', 'GUÁCIMA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('128', '2', '21', '06', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('129', '2', '21', '07', 'SABANILLA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('130', '2', '21', '08', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('131', '2', '21', '09', 'RÍO SEGUNDO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('132', '2', '21', '10', 'DESAMPARADOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('133', '2', '21', '11', 'TURRÚCARES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('134', '2', '21', '12', 'TAMBOR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('135', '2', '21', '13', 'GARITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('136', '2', '21', '14', 'SARAPIQUÍ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('137', '2', '22', '01', 'SAN RAMÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('138', '2', '22', '02', 'SANTIAGO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('139', '2', '22', '03', 'SAN JUAN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('140', '2', '22', '04', 'PIEDADES NORTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('141', '2', '22', '05', 'PIEDADES SUR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('142', '2', '22', '06', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('143', '2', '22', '07', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('144', '2', '22', '08', 'ÁNGELES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('145', '2', '22', '09', 'ALFARO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('146', '2', '22', '10', 'VOLIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('147', '2', '22', '11', 'CONCEPCIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('148', '2', '22', '12', 'ZAPOTAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('149', '2', '22', '13', 'PEÑAS BLANCAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('150', '2', '23', '01', 'GRECIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('151', '2', '23', '02', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('152', '2', '23', '03', 'SAN JOSÉ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('153', '2', '23', '04', 'SAN ROQUE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('154', '2', '23', '05', 'TACARES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('155', '2', '23', '06', 'RÍO CUARTO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('156', '2', '23', '07', 'PUENTE DE PIEDRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('157', '2', '23', '08', 'BOLÍVAR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('158', '2', '24', '01', 'SAN MATEO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('159', '2', '24', '02', 'DESMONTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('160', '2', '24', '03', 'JESÚS MARÍA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('161', '2', '24', '04', 'LABRADOR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('162', '2', '25', '01', 'ATENAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('163', '2', '25', '02', 'JESÚS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('164', '2', '25', '03', 'MERCEDES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('165', '2', '25', '04', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('166', '2', '25', '05', 'CONCEPCIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('167', '2', '25', '06', 'SAN JOSE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('168', '2', '25', '07', 'SANTA EULALIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('169', '2', '25', '08', 'ESCOBAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('170', '2', '26', '01', 'NARANJO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('171', '2', '26', '02', 'SAN MIGUEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('172', '2', '26', '03', 'SAN JOSÉ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('173', '2', '26', '04', 'CIRRÍ SUR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('174', '2', '26', '05', 'SAN JERÓNIMO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('175', '2', '26', '06', 'SAN JUAN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('176', '2', '26', '07', 'EL ROSARIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('177', '2', '26', '08', 'PALMITOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('178', '2', '27', '01', 'PALMARES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('179', '2', '27', '02', 'ZARAGOZA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('180', '2', '27', '03', 'BUENOS AIRES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('181', '2', '27', '04', 'SANTIAGO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('182', '2', '27', '05', 'CANDELARIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('183', '2', '27', '06', 'ESQUÍPULAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('184', '2', '27', '07', 'LA GRANJA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('185', '2', '28', '01', 'SAN PEDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('186', '2', '28', '02', 'SAN JUAN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('187', '2', '28', '03', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('188', '2', '28', '04', 'CARRILLOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('189', '2', '28', '05', 'SABANA REDONDA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('190', '2', '29', '01', 'OROTINA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('191', '2', '29', '02', 'EL MASTATE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('192', '2', '29', '03', 'HACIENDA VIEJA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('193', '2', '29', '04', 'COYOLAR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('194', '2', '29', '05', 'LA CEIBA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('195', '2', '30', '01', 'QUESADA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('196', '2', '30', '02', 'FLORENCIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('197', '2', '30', '03', 'BUENAVISTA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('198', '2', '30', '04', 'AGUAS ZARCAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('199', '2', '30', '05', 'VENECIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('200', '2', '30', '06', 'PITAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('201', '2', '30', '07', 'LA FORTUNA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('202', '2', '30', '08', 'LA TIGRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('203', '2', '30', '09', 'LA PALMERA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('204', '2', '30', '10', 'VENADO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('205', '2', '30', '11', 'CUTRIS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('206', '2', '30', '12', 'MONTERREY');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('207', '2', '30', '13', 'POCOSOL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('208', '2', '31', '01', 'ZARCERO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('209', '2', '31', '02', 'LAGUNA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('210', '2', '31', '04', 'GUADALUPE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('211', '2', '31', '05', 'PALMIRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('212', '2', '31', '06', 'ZAPOTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('213', '2', '31', '07', 'BRISAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('214', '2', '32', '01', 'SARCHÍ NORTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('215', '2', '32', '02', 'SARCHÍ SUR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('216', '2', '32', '03', 'TORO AMARILLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('217', '2', '32', '04', 'SAN PEDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('218', '2', '32', '05', 'RODRÍGUEZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('219', '2', '33', '01', 'UPALA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('220', '2', '33', '02', 'AGUAS CLARAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('221', '2', '33', '03', 'SAN JOSÉ o PIZOTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('222', '2', '33', '04', 'BIJAGUA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('223', '2', '33', '05', 'DELICIAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('224', '2', '33', '06', 'DOS RÍOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('225', '2', '33', '07', 'YOLILLAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('226', '2', '33', '08', 'CANALETE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('227', '2', '34', '01', 'LOS CHILES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('228', '2', '34', '02', 'CAÑO NEGRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('229', '2', '34', '03', 'EL AMPARO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('230', '2', '34', '04', 'SAN JORGE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('231', '2', '35', '02', 'BUENAVISTA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('232', '2', '35', '03', 'COTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('233', '2', '35', '04', 'KATIRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('234', '3', '36', '01', 'ORIENTAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('235', '3', '36', '02', 'OCCIDENTAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('236', '3', '36', '03', 'CARMEN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('237', '3', '36', '04', 'SAN NICOLÁS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('238', '3', '36', '05', 'AGUACALIENTE o SAN FRANCISCO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('239', '3', '36', '06', 'GUADALUPE o ARENILLA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('240', '3', '36', '07', 'CORRALILLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('241', '3', '36', '08', 'TIERRA BLANCA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('242', '3', '36', '09', 'DULCE NOMBRE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('243', '3', '36', '10', 'LLANO GRANDE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('244', '3', '36', '11', 'QUEBRADILLA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('245', '3', '37', '01', 'PARAÍSO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('246', '3', '37', '02', 'SANTIAGO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('247', '3', '37', '03', 'OROSI');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('248', '3', '37', '04', 'CACHÍ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('249', '3', '37', '05', 'LLANOS DE SANTA LUCÍA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('250', '3', '38', '01', 'TRES RÍOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('251', '3', '38', '02', 'SAN DIEGO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('252', '3', '38', '03', 'SAN JUAN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('253', '3', '38', '04', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('254', '3', '38', '05', 'CONCEPCIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('255', '3', '38', '06', 'DULCE NOMBRE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('256', '3', '38', '07', 'SAN RAMÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('257', '3', '38', '08', 'RÍO AZUL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('258', '3', '39', '01', 'JUAN VIÑAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('259', '3', '39', '02', 'TUCURRIQUE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('260', '3', '39', '03', 'PEJIBAYE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('261', '3', '40', '01', 'TURRIALBA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('262', '3', '40', '02', 'LA SUIZA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('263', '3', '40', '03', 'PERALTA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('264', '3', '40', '04', 'SANTA CRUZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('265', '3', '40', '05', 'SANTA TERESITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('266', '3', '40', '06', 'PAVONES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('267', '3', '40', '07', 'TUIS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('268', '3', '40', '08', 'TAYUTIC');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('269', '3', '40', '09', 'SANTA ROSA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('270', '3', '40', '10', 'TRES EQUIS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('271', '3', '40', '11', 'LA ISABEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('272', '3', '40', '12', 'CHIRRIPÓ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('273', '3', '41', '01', 'PACAYAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('274', '3', '41', '02', 'CERVANTES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('275', '3', '41', '03', 'CAPELLADES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('276', '3', '42', '01', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('277', '3', '42', '02', 'COT');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('278', '3', '42', '03', 'POTRERO CERRADO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('279', '3', '42', '04', 'CIPRESES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('280', '3', '42', '05', 'SANTA ROSA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('281', '3', '43', '01', 'EL TEJAR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('282', '3', '43', '02', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('283', '3', '43', '03', 'TOBOSI');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('284', '3', '43', '04', 'PATIO DE AGUA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('285', '4', '44', '01', 'HEREDIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('286', '4', '44', '02', 'MERCEDES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('287', '4', '44', '03', 'SAN FRANCISCO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('288', '4', '44', '04', 'ULLOA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('289', '4', '44', '05', 'VARABLANCA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('290', '4', '45', '01', 'BARVA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('291', '4', '45', '02', 'SAN PEDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('292', '4', '45', '03', 'SAN PABLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('293', '4', '45', '04', 'SAN ROQUE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('294', '4', '45', '05', 'SANTA LUCÍA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('295', '4', '45', '06', 'SAN JOSÉ DE LA MONTAÑA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('296', '4', '46', '02', 'SAN VICENTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('297', '4', '46', '03', 'SAN MIGUEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('298', '4', '46', '04', 'PARACITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('299', '4', '46', '05', 'SANTO TOMÁS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('300', '4', '46', '06', 'SANTA ROSA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('301', '4', '46', '07', 'TURES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('302', '4', '46', '08', 'PARÁ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('303', '4', '47', '01', 'SANTA BÁRBARA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('304', '4', '47', '02', 'SAN PEDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('305', '4', '47', '03', 'SAN JUAN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('306', '4', '47', '04', 'JESÚS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('307', '4', '47', '05', 'SANTO DOMINGO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('308', '4', '47', '06', 'PURABÁ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('309', '4', '48', '01', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('310', '4', '48', '02', 'SAN JOSECITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('311', '4', '48', '03', 'SANTIAGO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('312', '4', '48', '04', 'ÁNGELES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('313', '4', '48', '05', 'CONCEPCIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('314', '4', '49', '01', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('315', '4', '49', '02', 'SAN JOSÉ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('316', '4', '49', '03', 'CONCEPCIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('317', '4', '49', '04', 'SAN FRANCISCO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('318', '4', '50', '01', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('319', '4', '50', '02', 'LA RIBERA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('320', '4', '50', '03', 'LA ASUNCIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('321', '4', '51', '01', 'SAN JOAQUÍN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('322', '4', '51', '02', 'BARRANTES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('323', '4', '51', '03', 'LLORENTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('324', '4', '52', '01', 'SAN PABLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('325', '4', '53', '01', 'PUERTO VIEJO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('326', '4', '53', '02', 'LA VIRGEN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('327', '4', '53', '03', 'LAS HORQUETAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('328', '4', '53', '04', 'LLANURAS DEL GASPAR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('329', '4', '53', '05', 'CUREÑA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('330', '5', '54', '01', 'LIBERIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('331', '5', '54', '02', 'CAÑAS DULCES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('332', '5', '54', '03', 'MAYORGA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('333', '5', '54', '04', 'NACASCOLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('334', '5', '54', '05', 'CURUBANDÉ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('335', '5', '55', '01', 'NICOYA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('336', '5', '55', '02', 'MANSIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('337', '5', '55', '03', 'SAN ANTONIO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('338', '5', '55', '04', 'QUEBRADA HONDA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('339', '5', '55', '05', 'SÁMARA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('340', '5', '55', '06', 'NOSARA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('341', '5', '55', '07', 'BELÉN DE NOSARITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('342', '5', '56', '01', 'SANTA CRUZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('343', '5', '56', '02', 'BOLSÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('344', '5', '56', '03', 'VEINTISIETE DE ABRIL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('345', '5', '56', '04', 'TEMPATE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('346', '5', '56', '05', 'CARTAGENA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('347', '5', '56', '06', 'CUAJINIQUIL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('348', '5', '56', '07', 'DIRIÁ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('349', '5', '56', '08', 'CABO VELAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('350', '5', '56', '09', 'TAMARINDO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('351', '5', '57', '01', 'BAGACES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('352', '5', '57', '02', 'LA FORTUNA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('353', '5', '57', '03', 'MOGOTE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('354', '5', '57', '04', 'RÍO NARANJO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('355', '5', '58', '01', 'FILADELFIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('356', '5', '58', '02', 'PALMIRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('357', '5', '58', '03', 'SARDINAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('358', '5', '58', '04', 'BELÉN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('359', '5', '59', '01', 'CAÑAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('360', '5', '59', '02', 'PALMIRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('361', '5', '59', '03', 'SAN MIGUEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('362', '5', '59', '04', 'BEBEDERO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('363', '5', '59', '05', 'POROZAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('364', '5', '60', '01', 'LAS JUNTAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('365', '5', '60', '02', 'SIERRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('366', '5', '60', '03', 'SAN JUAN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('367', '5', '60', '04', 'COLORADO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('368', '5', '61', '01', 'TILARÁN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('369', '5', '61', '02', 'QUEBRADA GRANDE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('370', '5', '61', '03', 'TRONADORA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('371', '5', '61', '04', 'SANTA ROSA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('372', '5', '61', '05', 'LÍBANO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('373', '5', '61', '06', 'TIERRAS MORENAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('374', '5', '61', '07', 'ARENAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('375', '5', '62', '01', 'CARMONA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('376', '5', '62', '02', 'SANTA RITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('377', '5', '62', '03', 'ZAPOTAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('378', '5', '62', '04', 'SAN PABLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('379', '5', '62', '05', 'PORVENIR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('380', '5', '62', '06', 'BEJUCO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('381', '5', '63', '01', 'LA CRUZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('382', '5', '63', '02', 'SANTA CECILIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('383', '5', '63', '03', 'LA GARITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('384', '5', '63', '04', 'SANTA ELENA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('385', '5', '64', '01', 'HOJANCHA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('386', '5', '64', '02', 'MONTE ROMO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('387', '5', '64', '03', 'PUERTO CARRILLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('388', '5', '64', '04', 'HUACAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('389', '6', '65', '01', 'PUNTARENAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('390', '6', '65', '02', 'PITAHAYA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('391', '6', '65', '03', 'CHOMES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('392', '6', '65', '04', 'LEPANTO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('393', '6', '65', '05', 'PAQUERA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('394', '6', '65', '06', 'MANZANILLO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('395', '6', '65', '07', 'GUACIMAL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('396', '6', '65', '08', 'BARRANCA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('397', '6', '65', '09', 'MONTE VERDE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('398', '6', '65', '11', 'CÓBANO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('399', '6', '65', '12', 'CHACARITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('400', '6', '65', '13', 'CHIRA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('401', '6', '65', '14', 'ACAPULCO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('402', '6', '65', '15', 'EL ROBLE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('403', '6', '65', '16', 'ARANCIBIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('404', '6', '66', '01', 'ESPÍRITU SANTO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('405', '6', '66', '02', 'SAN JUAN GRANDE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('406', '6', '66', '03', 'MACACONA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('407', '6', '66', '04', 'SAN RAFAEL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('408', '6', '66', '05', 'SAN JERÓNIMO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('409', '6', '66', '06', 'CALDERA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('410', '6', '67', '01', 'BUENOS AIRES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('411', '6', '67', '02', 'VOLCÁN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('412', '6', '67', '03', 'POTRERO GRANDE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('413', '6', '67', '04', 'BORUCA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('414', '6', '67', '05', 'PILAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('415', '6', '67', '06', 'COLINAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('416', '6', '67', '07', 'CHÁNGUENA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('417', '6', '67', '08', 'BIOLLEY');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('418', '6', '67', '09', 'BRUNKA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('419', '6', '68', '01', 'MIRAMAR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('420', '6', '68', '02', 'LA UNIÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('421', '6', '68', '03', 'SAN ISIDRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('422', '6', '69', '01', 'PUERTO CORTÉS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('423', '6', '69', '02', 'PALMAR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('424', '6', '69', '03', 'SIERPE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('425', '6', '69', '04', 'BAHÍA BALLENA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('426', '6', '69', '05', 'PIEDRAS BLANCAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('427', '6', '69', '06', 'BAHÍA DRAKE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('428', '6', '70', '01', 'QUEPOS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('429', '6', '70', '02', 'SAVEGRE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('430', '6', '70', '03', 'NARANJITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('431', '6', '71', '01', 'GOLFITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('432', '6', '71', '02', 'PUERTO JIMÉNEZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('433', '6', '71', '03', 'GUAYCARÁ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('434', '6', '71', '04', 'PAVÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('435', '6', '72', '01', 'SAN VITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('436', '6', '72', '02', 'SABALITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('437', '6', '72', '03', 'AGUABUENA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('438', '6', '72', '04', 'LIMONCITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('439', '6', '72', '05', 'PITTIER');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('440', '6', '72', '06', 'GUTIERREZ BRAUN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('441', '6', '73', '01', 'PARRITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('442', '6', '74', '01', 'CORREDOR');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('443', '6', '74', '02', 'LA CUESTA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('444', '6', '74', '03', 'CANOAS');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('445', '6', '74', '04', 'LAUREL');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('446', '6', '75', '01', 'JACÓ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('447', '6', '75', '02', 'TÁRCOLES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('448', '7', '76', '01', 'LIMÓN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('449', '7', '76', '02', 'VALLE LA ESTRELLA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('450', '7', '76', '04', 'MATAMA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('451', '7', '77', '01', 'GUÁPILES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('452', '7', '77', '02', 'JIMÉNEZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('453', '7', '77', '03', 'RITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('454', '7', '77', '04', 'ROXANA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('455', '7', '77', '05', 'CARIARI');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('456', '7', '77', '06', 'COLORADO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('457', '7', '77', '07', 'LA COLONIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('458', '7', '78', '01', 'SIQUIRRES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('459', '7', '78', '02', 'PACUARITO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('460', '7', '78', '03', 'FLORIDA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('461', '7', '78', '04', 'GERMANIA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('462', '7', '78', '05', 'EL CAIRO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('463', '7', '78', '06', 'ALEGRÍA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('464', '7', '79', '01', 'BRATSI');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('465', '7', '79', '02', 'SIXAOLA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('466', '7', '79', '03', 'CAHUITA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('467', '7', '79', '04', 'TELIRE');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('468', '7', '80', '01', 'MATINA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('469', '7', '80', '02', 'BATÁN');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('470', '7', '80', '03', 'CARRANDI');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('471', '7', '81', '01', 'GUÁCIMO');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('472', '7', '81', '02', 'MERCEDES');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('473', '7', '81', '03', 'POCORA');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('474', '7', '81', '04', 'RÍO JIMÉNEZ');
INSERT INTO distrito (id, codigoProvincia, codigoCanton, codigo, distrito) VALUES ('475', '7', '81', '05', 'DUACARÍ');


